### PR TITLE
Added sync on_resolve extension.

### PR DESCRIPTION
**Pull request by trollfot**

### CODE REVIEW

**Comment by ThirVondukr** [comment]
Looks good, I'll make a couple of changes if you don't mind - I think it should be possible to add both (sync and async) `on_resolve` methods to an extension class, so `on_resolve` should be renamed to `on_resolve_async`.
There are also some minor formatting issues but I can fix them myself (or you can install [taskfile](https://taskfile.dev/) to run all the tasks and fix them yourself too.

**Comment by ThirVondukr** [comment]
@trollfot Just pinging you in case you didn't see the message, I can merge the branch and change some things that I want, if you don't mind.

**Comment by trollfot** [comment]
@ThirVondukr Hey. Sorry, I got swamped today. I can try and do the changes tomorrow !

**Comment by trollfot** [comment]
"I can merge the branch and change some things that I want, if you don't mind."  If you feel like it's not a problem for you to spend time on it, please go for it, i'm happy either way

**Comment by ThirVondukr** [comment]
No, it's not a problem, gonna finish it tomorrow

**Pull request merged**
